In [1]:
import pandas as pd
df = pd.read_csv('Global_Mobility_Report.csv')

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [2]:
df.head()

country_region_code        country_region sub_region_1 sub_region_2  \
0                  AE  United Arab Emirates          NaN          NaN   
1                  AE  United Arab Emirates          NaN          NaN   
2                  AE  United Arab Emirates          NaN          NaN   
3                  AE  United Arab Emirates          NaN          NaN   
4                  AE  United Arab Emirates          NaN          NaN   

  iso_3166_2_code  census_fips_code        date  \
0             NaN               NaN  2020-02-15   
1             NaN               NaN  2020-02-16   
2             NaN               NaN  2020-02-17   
3             NaN               NaN  2020-02-18   
4             NaN               NaN  2020-02-19   

   retail_and_recreation_percent_change_from_baseline  \
0                                                0.0    
1                                                1.0    
2                                               -1.0    
3                                               -2.0    
4                                               -2.0    

   grocery_and_pharmacy_percent_change_from_baseline  \
0                                                4.0   
1                                                4.0   
2                                                1.0   
3                                                1.0   
4                                                0.0   

   parks_percent_change_from_baseline  \
0                                 5.0   
1                                 4.0   
2                                 5.0   
3                                 5.0   
4                                 4.0   

   transit_stations_percent_change_from_baseline  \
0                                            0.0   
1                                            1.0   
2                                            1.0   
3                                            0.0   
4                                           -1.0   

   workplaces_percent_change_from_baseline  \
0                                      2.0   
1                                      2.0   
2                                      2.0   
3                                      2.0   
4                                      2.0   

   residential_percent_change_from_baseline  
0                                       1.0  
1                                       1.0  
2                                       1.0  
3                                       1.0  
4                                       1.0

In [3]:
df_ph = df[df['country_region_code'] == 'PH']

In [4]:
df_ph.head()

country_region_code country_region sub_region_1 sub_region_2  \
168835                  PH    Philippines          NaN          NaN   
168836                  PH    Philippines          NaN          NaN   
168837                  PH    Philippines          NaN          NaN   
168838                  PH    Philippines          NaN          NaN   
168839                  PH    Philippines          NaN          NaN   

       iso_3166_2_code  census_fips_code        date  \
168835             NaN               NaN  2020-02-15   
168836             NaN               NaN  2020-02-16   
168837             NaN               NaN  2020-02-17   
168838             NaN               NaN  2020-02-18   
168839             NaN               NaN  2020-02-19   

        retail_and_recreation_percent_change_from_baseline  \
168835                                                7.0    
168836                                                3.0    
168837                                               -1.0    
168838                                                0.0    
168839                                               -3.0    

        grocery_and_pharmacy_percent_change_from_baseline  \
168835                                                4.0   
168836                                                5.0   
168837                                                0.0   
168838                                                1.0   
168839                                               -3.0   

        parks_percent_change_from_baseline  \
168835                                -1.0   
168836                                -2.0   
168837                                -3.0   
168838                                -3.0   
168839                                -4.0   

        transit_stations_percent_change_from_baseline  \
168835                                            1.0   
168836                                           -3.0   
168837                                           -2.0   
168838                                            0.0   
168839                                           -6.0   

        workplaces_percent_change_from_baseline  \
168835                                      6.0   
168836                                      1.0   
168837                                      8.0   
168838                                      5.0   
168839                                      5.0   

        residential_percent_change_from_baseline  
168835                                       0.0  
168836                                       1.0  
168837                                       1.0  
168838                                       0.0  
168839                                       1.0

In [5]:
len(df_ph)

2322

In [6]:
df_ph['sub_region_1'].unique()

array([nan, 'Autonomous Region in Muslim Mindanao', 'Bicol',
       'Cagayan Valley', 'Calabarzon', 'Caraga', 'Central Luzon',
       'Central Visayas', 'Cordillera Administrative Region',
       'Davao Region', 'Eastern Visayas', 'Ilocos Region', 'Metro Manila',
       'MIMAROPA', 'Northern Mindanao', 'SOCCSKSARGEN', 'Western Visayas',
       'Zamboanga Peninsula'], dtype=object)

In [7]:
df_ph['sub_region_2'].unique()

array([nan], dtype=object)

In [9]:
df_ph['iso_3166_2_code'].unique()

array([nan, 'PH-14', 'PH-05', 'PH-02', 'PH-40', 'PH-13', 'PH-03', 'PH-07',
       'PH-15', 'PH-11', 'PH-08', 'PH-01', 'PH-00', 'PH-41', 'PH-10',
       'PH-12', 'PH-06', 'PH-09'], dtype=object)

In [10]:
df_ph['census_fips_code'].unique()

array([nan])

In [11]:
df_ph.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2322 entries, 168835 to 171156
Data columns (total 13 columns):
 #   Column                                              Non-Null Count  Dtype  
---  ------                                              --------------  -----  
 0   country_region_code                                 2322 non-null   object 
 1   country_region                                      2322 non-null   object 
 2   sub_region_1                                        2193 non-null   object 
 3   sub_region_2                                        0 non-null      object 
 4   iso_3166_2_code                                     2193 non-null   object 
 5   census_fips_code                                    0 non-null      float64
 6   date                                                2322 non-null   object 
 7   retail_and_recreation_percent_change_from_baseline  2322 non-null   float64
 8   grocery_and_pharmacy_percent_change_from_baseline   2322 non-null   flo

In [12]:
df_ph['date1'] = pd.to_datetime(df_ph['date'])

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [13]:
df_ph.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2322 entries, 168835 to 171156
Data columns (total 14 columns):
 #   Column                                              Non-Null Count  Dtype         
---  ------                                              --------------  -----         
 0   country_region_code                                 2322 non-null   object        
 1   country_region                                      2322 non-null   object        
 2   sub_region_1                                        2193 non-null   object        
 3   sub_region_2                                        0 non-null      object        
 4   iso_3166_2_code                                     2193 non-null   object        
 5   census_fips_code                                    0 non-null      float64       
 6   date                                                2322 non-null   object        
 7   retail_and_recreation_percent_change_from_baseline  2322 non-null   float64       
 8   g

In [14]:
min(df_ph['date'])

'2020-02-15'

In [15]:
max(df_ph['date'])

'2020-06-22'

In [16]:
df_ph_manila = df_ph[df_ph['sub_region_1'] == 'Metro Manila']

In [19]:
import numpy as np
import matplotlib.pyplot as plt  
from matplotlib.animation import FuncAnimation, PillowWriter  
import matplotlib.dates as mdates
from matplotlib.ticker import FuncFormatter
from matplotlib.dates import DateFormatter

%matplotlib notebook  

In [98]:
x_d = df_ph_manila['date1']

y = df_ph_manila['retail_and_recreation_percent_change_from_baseline']
y1 = df_ph_manila['grocery_and_pharmacy_percent_change_from_baseline']
y2 = df_ph_manila['parks_percent_change_from_baseline']
y3 = df_ph_manila['transit_stations_percent_change_from_baseline']
y4 = df_ph_manila['workplaces_percent_change_from_baseline']
y5 = df_ph_manila['residential_percent_change_from_baseline']

fig, ax = plt.subplots(figsize=(10,5), dpi=500)  
x, y_, y1_, y2_, y3_, y4_, y5_ = [], [], [], [], [], [], []  
ln1, = plt.plot([], [], color='r', label= 'Retail and Recreation')  
ln2, = plt.plot([], [], color='b', label= 'Grocery and Pharmacy')
ln3, = plt.plot([], [], color='g', label= 'Parks')  
ln4, = plt.plot([], [], color='c', label= 'Transit Stations')
ln5, = plt.plot([], [], color='m', label= 'Workplaces') 
ln6, = plt.plot([], [], color='y', label= 'Residential')


import datetime as dt


plt.title('Mobility of Filipinos in target locations during various quarantine periods (Metro Manila)')
plt.ylabel('% change compared to baseline')
plt.axhline(0, color = 'k')
plt.axvline(dt.datetime(2020, 3, 15), color = 'k', linestyle = '--', alpha=0.5)
plt.axvline(dt.datetime(2020, 6, 1), color = 'k', linestyle = '--', alpha=0.5)
plt.axvspan(dt.datetime(2020, 3, 15), dt.datetime(2020, 6, 1), ymin=0, ymax=0.625, alpha=0.3, color='green')
# plt.legend()
plt.text(dt.datetime(2020, 3, 18),-10,'ECQ Period', fontsize=10, style='italic')
plt.text(dt.datetime(2020, 2, 19),-52,'Workplaces', fontsize=9, fontweight='bold')
plt.text(dt.datetime(2020, 2, 26),20,'Parks', fontsize=9, fontweight='bold')
plt.text(dt.datetime(2020, 5, 14),45,'Residential', fontsize=9, fontweight='bold')
plt.text(dt.datetime(2020, 5, 1),-35,'Grocery and Pharmacy', fontsize=9, fontweight='bold')
plt.text(dt.datetime(2020, 4, 15),-89,'Retail', fontsize=9, fontweight='bold')
plt.text(dt.datetime(2020, 3, 17),-97,'Transit Stations', fontsize=9, fontweight='bold')
plt.text(dt.datetime(2020, 3, 8),55,'Start of', fontsize=7)
plt.text(dt.datetime(2020, 3, 8),51,'ECQ', fontsize=7)
plt.text(dt.datetime(2020, 6, 2),55,'Start of', fontsize=7)
plt.text(dt.datetime(2020, 6, 2),51,'GCQ', fontsize=7)


def init():  
    ax.set_xlim(0, len(x_d))  
    ax.set_ylim(-100, 60)
    ax.set_xlim(min(x_d), max(x_d))  
    ax.set_ylim(-100, 60)
    date_form = DateFormatter("%b-%d")
    ax.xaxis.set_major_formatter(date_form)
  
def update(i):  
    x.append(x_d.iloc[int(i)]) 
    y_.append(y.iloc[int(i)])  
    y1_.append(y1.iloc[int(i)])
    y2_.append(y2.iloc[int(i)]) 
    y3_.append(y3.iloc[int(i)]) 
    y4_.append(y4.iloc[int(i)]) 
    y5_.append(y5.iloc[int(i)]) 
    ln1.set_data(x, y_)  
    ln2.set_data(x, y1_) 
    ln3.set_data(x, y2_)  
    ln4.set_data(x, y3_) 
    ln5.set_data(x, y4_)  
    ln6.set_data(x, y5_) 
    

ani = FuncAnimation(fig, update, np.linspace(0, len(x_d), len(x_d)+1), init_func=init, repeat = True, blit = True)
plt.show()


# writer = PillowWriter(fps=25)  
# ani.save("demo.gif", writer=writer)  

<IPython.core.display.Javascript object>

IndexError: single positional indexer is out-of-bounds